# .github/workflows/aniList.yaml
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: hengvvang
          template: classic
          base: ""
          config_octicon: yes
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: hengvvang
